# try to build the octave development branch (aka default) to test image-acquisition.
# Just with minimal dependencies, no Qhull, RapidJSON, BLAS, Qt and so on

FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y g++ make\
  libpcre3-dev libblas-dev liblapack-dev gfortran libtool libreadline-dev wget lzip mercurial automake

RUN apt-get update && apt-get --no-install-recommends install -y pkg-config patch mercurial git gperf bison libv4l-dev libfltk1.3-dev 

RUN hg clone https://hg.octave.org/octave
RUN cd octave && ./bootstrap && mkdir .build && cd .build && ../configure 

RUN apt-get update && apt-get --no-install-recommends install -y flex bison librsvg2-bin icoutils texinfo

RUN cd octave/.build && make -j$(nproc)
RUN cd octave/.build && make install

COPY ./image-acquisition-*.tar.gz /app/
RUN octave --eval "pkg install -verbose image-acquisition-*.tar.gz"
CMD ["/usr/local/bin/octave"]

#CMD ["/usr/bin/bash"]
