#!/bin/bash
## Octave-Forge: image acquisition package bootstrap script
## Run this to generate the configure script

set -e      # halt if unhandled error
autoheader  # generate config.h.in
autoconf    # generate configure script
